version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    networks:
      - flask-network
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    command: bash -c "flask run --host=0.0.0.0 --port=5001"


networks:
  flask-network:
    driver: bridge
